# Generated by Django 5.1.2 on 2024-10-23 08:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emp_rprt", "0003_alter_empuser_options_alter_empuser_managers_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EmpPosition",
            new_name="Position",
        ),
    ]
