# Generated by Django 5.1.2 on 2024-10-24 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emp_rprt", "0005_workflowstage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Position",
            new_name="Department",
        ),
        migrations.CreateModel(
            name="UserDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emp_rprt.department",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emp_rprt.workdetail",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserPosition",
        ),
        migrations.AddField(
            model_name="progress",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="emp_rprt.department",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="progress",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="progress",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        
    ]
