# Generated by Django 5.1.2 on 2024-10-24 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emp_rprt", "0006_progress_department_alter_progress_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="progress",
            name="department",
        ),
    ]
