# Generated by Django 5.1.2 on 2024-10-24 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emp_rprt", "0008_remove_userdepartment_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="emp_rprt.department",
            ),
        ),
        migrations.AddField(
            model_name="userdepartment",
            name="department",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="emp_rprt.department",
            ),
        ),
    ]
