# Generated by Django 5.1.2 on 2024-10-24 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emp_rprt", "0009_progress_department_userdepartment_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="workflow_stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="emp_rprt.workflowstage",
            ),
        ),
        migrations.AddField(
            model_name="workflowstage",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="progressupdated",
            name="status_changed_to",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workflowstage",
            name="title",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
