# Generated by Django 5.1.2 on 2024-10-25 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emp_rprt", "0011_progressupdated_workflow_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progress",
            name="work",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="emp_rprt.workdetail",
            ),
        ),
        migrations.AlterField(
            model_name="progressupdated",
            name="work",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="emp_rprt.workdetail",
            ),
        ),
        migrations.AlterField(
            model_name="userdepartment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userdepartment",
            name="work",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="emp_rprt.workflowstage"
            ),
        ),
    ]
