# Generated by Django 5.1.2 on 2024-11-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emp_rprt", "0013_products_cp_products_sp_products_variant_colors_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="variant_quantity",
            new_name="quantity",
        ),
        migrations.RemoveField(
            model_name="products",
            name="variant_colors",
        ),
        migrations.AddField(
            model_name="products",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="products",
            name="size",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="products",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
