# Generated by Django 5.1.2 on 2024-11-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emp_rprt", "0014_rename_variant_quantity_products_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
